// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2dhLzs75AyImyIc0Wrz20tpTbc4QHaUQ',
    appId: '1:446589487356:web:0b7a52de839b9a6d9eef79',
    messagingSenderId: '446589487356',
    projectId: 'munchies-a5aab',
    authDomain: 'munchies-a5aab.firebaseapp.com',
    storageBucket: 'munchies-a5aab.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf3qvh0mTqxo7HelP_hLvDkP-IM1yEGaY',
    appId: '1:446589487356:ios:a4363343eb0393bb9eef79',
    messagingSenderId: '446589487356',
    projectId: 'munchies-a5aab',
    storageBucket: 'munchies-a5aab.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2dhLzs75AyImyIc0Wrz20tpTbc4QHaUQ',
    appId: '1:446589487356:web:019ab085cbe9f8a49eef79',
    messagingSenderId: '446589487356',
    projectId: 'munchies-a5aab',
    authDomain: 'munchies-a5aab.firebaseapp.com',
    storageBucket: 'munchies-a5aab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf3qvh0mTqxo7HelP_hLvDkP-IM1yEGaY',
    appId: '1:446589487356:ios:a4363343eb0393bb9eef79',
    messagingSenderId: '446589487356',
    projectId: 'munchies-a5aab',
    storageBucket: 'munchies-a5aab.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHnlw9ebGDbuxYJruQ3wq-pufMu9tn54U',
    appId: '1:446589487356:android:178fbcb5c4986be89eef79',
    messagingSenderId: '446589487356',
    projectId: 'munchies-a5aab',
    storageBucket: 'munchies-a5aab.firebasestorage.app',
  );

}